// Original A-5 sender subgraph, independently checked against the archived raw
// bytes (SHA256 d43cce5578ee2f16b27c8b06bff30743e3e2dffc796d033811e565d5d578c52e).
// These expectations are literal path ledgers, not generated by the executor.
// https://github.com/ErroneousBosh/j106roms/blob/26926a04ff1939106820313e71e34b4ca2f67070/ic1.txt
// NEC Stock500375 (April1987), printed7-3/7-4,9-5..9-7,12-21 supplies distinct
// TXB/shifter, FST,16-state IRQ entry and EI's one-following-instruction rule.
// https://drive.google.com/file/d/0B44NKm9yPA1bNDFXZnFrdG1PdDA/view
// Producer09E8 entry excludes caller CALF; consumer times include IRQ entry.
// FD/F9 are route markers, never bytes on the wire. The48-slot FIFO leaves one
// slot unused.0837 is the actual FD/command/value caller, not an invented idle.
// Configured idle baud phase/peripheral-first ties are explicit scenarios.
// AwaitingForeground is a real supported-graph frontier; no later CPU idle or
// RXB-ready timing is inferred. No ROM, private report or external file is needed.
#include "../Source/DSP/YouKnowFirmwareAssignerTrace.h"
#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <span>
#include <tuple>
#include <vector>
using A = youknow::FirmwareAssignerTrace;
namespace U = youknow::FirmwareUartTrace;
using K = A::EventKind;
unsigned assertions = 0, failures = 0;
void check(bool result, const char *message) {
    ++assertions;
    if (!result && failures++ < 24)
        std::cerr << message << '\n';
}
auto registers(const A::Registers &r) {
    return std::tie(r.a, r.b, r.c, r.d, r.e, r.h, r.l, r.ea, r.v, r.alternateA, r.alternateB,
                    r.alternateC, r.alternateD, r.alternateE, r.alternateH, r.alternateL,
                    r.alternateEa, r.alternateV, r.pc, r.sp, r.carry, r.skip);
}
auto pending(const A::Pending &p) {
    return std::tie(p.kind, p.start, p.remaining, p.address, p.returnPc, p.savedPsw, p.skipped);
}
bool sameCpu(const A::State &a, const A::State &b) {
    return a.ram == b.ram && registers(a.registers) == registers(b.registers) &&
           pending(a.pending) == pending(b.pending) &&
           std::tie(a.now, a.mkh, a.eiDeferred, a.opaquePsw, a.interruptEnabled, a.fsr, a.fad,
                    a.foregroundBoundary) == std::tie(b.now, b.mkh, b.eiDeferred, b.opaquePsw,
                                                      b.interruptEnabled, b.fsr, b.fad,
                                                      b.foregroundBoundary);
}
auto uartState(const U::State &s) {
    return std::tie(s.now, s.transmitEnabled, s.txBufferFull, s.txBuffer, s.fst, s.frameActive,
                    s.frameByte, s.bitIndex, s.frameOrdinal, s.frameStart, s.nextBit, s.idleLaunch,
                    s.stopCenterObserved, s.portC, s.txd, s.moduleRxD, s.midiLogic);
}
auto event(const A::Event &e) { return std::tie(e.kind, e.states, e.pc, e.address, e.value); }
auto wireEvent(const U::Event &e) {
    return std::tie(e.kind, e.states, e.frameOrdinal, e.value, e.bitIndex, e.pinLevels);
}
struct Scene {
    A::State cpu;
    U::State uart;
};
struct Run : Scene {
    A::Status status = A::Status::ReachedTarget;
    std::vector<A::Event> events;
    std::vector<U::Event> wire;
    std::size_t consumed = 0;
};
Scene procedure(unsigned pc, unsigned value = 0, unsigned command = 0, unsigned head = 0) {
    Scene s;
    s.cpu.registers.pc = pc;
    s.cpu.registers.a = value;
    s.cpu.registers.b = command;
    s.cpu.interruptEnabled = false;
    s.cpu.mkh = 0;
    s.cpu.ram[0xfd] = 0;
    s.cpu.ram[0xfe] = 0xf0;
    s.cpu.ram[0xc1] = s.cpu.ram[0xc2] = static_cast<std::uint8_t>(head);
    return s;
}
Scene irq(std::span<const std::uint8_t> queue = {}, unsigned head = 0, unsigned port = 0xfd) {
    Scene s;
    s.cpu.registers.pc = 0xf000;
    s.cpu.registers.sp = 0xffff;
    s.cpu.foregroundBoundary = true;
    s.cpu.mkh = 0;
    s.uart.portC = static_cast<std::uint8_t>(port);
    s.cpu.ram[0xc1] = static_cast<std::uint8_t>(head);
    s.cpu.ram[0xc2] = static_cast<std::uint8_t>((head + queue.size()) % 48);
    for (unsigned i = 0; i < queue.size(); ++i)
        s.cpu.ram[(head + i) % 48] = queue[i];
    return s;
}
Run run(Scene seed, std::uint64_t target, unsigned step = 10000, U::Configuration config = {},
        std::span<const A::Request> requests = {}, unsigned cpuFill = 0, unsigned uartFill = 0,
        unsigned wireCapacity = 128) {
    Run r;
    static_cast<Scene &>(r) = seed;
    A::Events events;
    events.count = cpuFill;
    std::array<U::Event, 128> storage{};
    U::EventBuffer wire{storage.data(), wireCapacity, uartFill};
    bool initial = true;
    std::uint64_t deadline = std::min(target, r.cpu.now + step);
    for (unsigned calls = 0; calls < 1000000; ++calls) {
        auto result = A::advanceTo(r.cpu, r.uart, config, requests.subspan(r.consumed), deadline,
                                   events, wire);
        r.consumed += result.consumedRequests;
        r.status = result.status;
        r.events.insert(r.events.end(), events.entries.begin() + (initial ? cpuFill : 0),
                        events.entries.begin() + events.count);
        r.wire.insert(r.wire.end(), storage.begin() + (initial ? uartFill : 0),
                      storage.begin() + wire.count);
        initial = false;
        events.count = 0;
        wire.count = 0;
        if (result.status == A::Status::OutputFull)
            continue;
        if (result.status != A::Status::ReachedTarget || deadline == target)
            return r;
        deadline = std::min(target, deadline + step);
    }
    check(false, "bounded advance/drain loop terminates");
    return r;
}
const A::Event *findEvent(const Run &r, K kind, unsigned address = 0xffffffff) {
    const auto i = std::find_if(r.events.begin(), r.events.end(), [&](const auto &e) {
        return e.kind == kind && (address == 0xffffffff || e.address == address);
    });
    return i == r.events.end() ? nullptr : &*i;
}
void at(const Run &r, K kind, unsigned address, std::uint64_t time, unsigned value) {
    const auto *e = findEvent(r, kind, address);
    check(e && e->states == time && e->value == value,
          "original-byte event value/completion timestamp");
}
void equality(const Run &a, const Run &b) {
    check(a.status == b.status && a.consumed == b.consumed,
          "chunk/drain terminal status and input consumption");
    check(sameCpu(a.cpu, b.cpu), "all CPU registers/RAM/pending/flags invariant to chunk/drain");
    check(uartState(a.uart) == uartState(b.uart), "all UART state invariant to chunk/drain");
    check(a.events.size() == b.events.size(), "CPU event count invariant to chunk/drain");
    check(a.wire.size() == b.wire.size(), "UART event count invariant to chunk/drain");
    for (unsigned i = 0; i < std::min(a.events.size(), b.events.size()); ++i)
        check(event(a.events[i]) == event(b.events[i]), "every CPU event invariant to chunk/drain");
    for (unsigned i = 0; i < std::min(a.wire.size(), b.wire.size()); ++i)
        check(wireEvent(a.wire[i]) == wireEvent(b.wire[i]),
              "every UART event invariant to chunk/drain");
}
void literalLedgers() {
    const std::array<std::uint8_t, 1> byte{0x88};
    for (unsigned head = 0; head < 48; ++head) {
        auto producer = run(procedure(0x9e8, 0x88, 0, head), 228);
        check(producer.status == A::Status::AwaitingForeground && producer.cpu.now == 228,
              "09E8 producer returns after228 original states");
        at(producer, K::RamWrite, 0xff00 + head, 134, 0x88);
        at(producer, K::RamWrite, 0xffc2, 168, (head + 1) % 48);
        at(producer, K::MaskWrite, 0, 158, 7);
        check(producer.cpu.mkh == 0 && producer.cpu.registers.sp == 0xffff,
              "producer clears MKH low3 bits and restores caller stack");
        check(producer.cpu.ram[0xc1] == head && producer.cpu.ram[0xc2] == (head + 1) % 48,
              "producer publishes exactly one slot with48-position wrap");
        auto consumer = run(irq(byte, head), 225);
        check(consumer.status == A::Status::AwaitingForeground && consumer.cpu.now == 225,
              "ordinary data IRQ entry through RETI225states");
        at(consumer, K::TxBufferWrite, 0xd8, 172, 0x88);
        at(consumer, K::RamWrite, 0xffc1, 200, (head + 1) % 48);
        check(consumer.uart.txBufferFull && !consumer.uart.frameActive &&
                  consumer.uart.idleLaunch == 256,
              "TXB admission172 precedes configured launch256");
    }
    auto empty = run(irq(), 146);
    check(empty.status == A::Status::AwaitingForeground && empty.cpu.now == 146 &&
              empty.cpu.mkh == 4,
          "empty queue masks transmit and returns146states");
    at(empty, K::MaskWrite, 0, 121, 4);
    for (unsigned marker : {0xfd, 0xf9})
        for (unsigned initial : {0xfd, 0xf9}) {
            const std::array<std::uint8_t, 2> queue{static_cast<std::uint8_t>(marker), 0x88};
            const auto pcTime = (marker == 0xfd ? 220u : 234u) + (marker == initial ? 0u : 1531u);
            const auto r = run(irq(queue, 47, initial), pcTime + 165);
            at(r, K::PortCWrite, 2, pcTime, marker);
            at(r, K::TxBufferWrite, 0xd8, pcTime + 112, 0x88);
            check(std::count_if(r.events.begin(), r.events.end(),
                                [](auto &e) { return e.kind == K::TxBufferWrite; }) == 1,
                  "route markers are never written to TXB");
            check(r.cpu.ram[0xc1] == 1, "marker and data consumption independently wrap FIFO");
        }
}
void callerAndChunking() {
    for (unsigned command : {0x88, 0x8e, 0x95})
        for (unsigned value : {0, 60, 127}) {
            auto s = procedure(0x837, value, command);
            auto r = run(s, 10000);
            check(r.status == A::Status::AwaitingForeground && r.cpu.now == 752,
                  "actual0837 caller completes752states without interrupts");
            const std::array<unsigned, 3> values{0xfd, command, value};
            for (unsigned i = 0; i < 3; ++i) {
                at(r, K::RamWrite, 0xff00 + i, 158 + 245 * i, values[i]);
                const auto found =
                    std::find_if(r.events.begin(), r.events.end(), [&](const auto &e) {
                        return e.kind == K::RamWrite && e.address == 0xffc2 && e.value == i + 1;
                    });
                check(found != r.events.end() && found->states == 192 + 245 * i,
                      "actual caller publishes marker/command/value at192,437,682");
            }
        }
    for (unsigned phase : {0, 1, 37, 127})
        for (unsigned port : {0xfd, 0xf9}) {
            auto s = procedure(0x837, 0x20, 0x98);
            s.cpu.interruptEnabled = true;
            s.cpu.mkh = 4;
            s.uart.portC = static_cast<std::uint8_t>(port);
            auto full = run(s, 20000, 20000, U::Configuration{static_cast<std::uint8_t>(phase)});
            check(full.status == A::Status::AwaitingForeground,
                  "preempted actual caller stops at known foreground boundary");
            check(full.cpu.now < 20000 && full.cpu.ram[0xc1] == full.cpu.ram[0xc2],
                  "all three slots consumed before supported sender frontier");
            std::vector<unsigned> sent;
            for (const auto &e : full.events)
                if (e.kind == K::TxBufferWrite)
                    sent.push_back(e.value);
            check(sent == std::vector<unsigned>{0x98, 0x20},
                  "preempted actual caller admits exactly command and value");
            for (unsigned step : {1, 7, 16, 83, 4096})
                equality(full,
                         run(s, 20000, step, U::Configuration{static_cast<std::uint8_t>(phase)}));
            for (unsigned free : {0, 1, 2, 3, 7})
                equality(full, run(s, 20000, 83, U::Configuration{static_cast<std::uint8_t>(phase)},
                                   {}, 512 - free, 8 - free, 8));
        }
}
void interruptsAndBoundaries() {
    const std::array<std::uint8_t, 1> byte{0x88};
    auto s = irq(byte);
    auto &r = s.cpu.registers;
    r.a = 0x12;
    r.b = 0x23;
    r.c = 0x34;
    r.d = 0x45;
    r.e = 0x56;
    r.h = 0x67;
    r.l = 0x78;
    r.ea = 0x89;
    r.alternateA = 0x98;
    r.alternateB = 0x87;
    r.alternateC = 0x76;
    r.alternateD = 0x65;
    r.alternateE = 0x54;
    r.alternateH = 0x43;
    r.alternateL = 0x32;
    r.alternateEa = 0x21;
    r.carry = true;
    r.skip = true;
    s.cpu.opaquePsw = 0x5c;
    auto restored = run(s, 225);
    check(restored.cpu.registers.a == r.a && restored.cpu.registers.b == r.b &&
              restored.cpu.registers.c == r.c && restored.cpu.registers.d == r.d &&
              restored.cpu.registers.e == r.e && restored.cpu.registers.h == r.h &&
              restored.cpu.registers.l == r.l && restored.cpu.registers.ea == r.ea,
          "actual EXA/EXX path restores foreground general registers");
    check(restored.cpu.registers.carry && restored.cpu.registers.skip &&
              restored.cpu.opaquePsw == 0x5c && restored.cpu.registers.sp == 0xffff,
          "physical stack restores caller carry/skip/opaque PSW and SP");
    check(restored.cpu.ram[0xfe] == 0x7d && restored.cpu.ram[0xfd] == 0xf0 &&
              restored.cpu.ram[0xfc] == 0,
          "16-state entry writes saved PSW/PC to actual RAM stack");
    equality(restored, run(s, 225, 1));
    equality(restored, run(s, 225, 225, {}, {}, 510, 8, 8));
    auto partial = run(irq(byte), 15);
    check(partial.cpu.pending.kind == A::PendingKind::InterruptEntry &&
              partial.cpu.pending.remaining == 1 && partial.cpu.registers.sp == 0xffff,
          "partial16-state interrupt entry has not yet committed stack");
    auto entry = run(irq(byte), 16);
    check(entry.cpu.registers.sp == 0xfffc, "entry commits exactly at16-state completion");
    equality(entry, run(irq(byte), 16, 16, {}, {}, 511, 0, 8));
    const std::array<std::uint8_t, 2> queue{0xf9, 0x88};
    for (unsigned poll = 0; poll < 48; ++poll) {
        // Independent raw path: first SKIT completion201, subsequent32-state
        // iterations. The last wrap skips the JR; FSR diverts before PC/C1.
        const std::array<A::Request, 1> request{{{201 + 32 * poll, A::RequestKind::Receive}}};
        auto diverted = run(irq(queue), 4000, 4000, {}, request);
        check(diverted.status == A::Status::UnsupportedPath &&
                  diverted.cpu.registers.pc == 0x05a0 && diverted.cpu.ram[0xc1] == 0 &&
                  diverted.cpu.now == 215 + 32 * poll,
              "FSR route-guard diversion stops before RX parser without consuming marker");
        check(!findEvent(diverted, K::PortCWrite) && !findEvent(diverted, K::TxBufferWrite),
              "RX-diverted marker emits neither route nor wire write");
        equality(diverted, run(irq(queue), 4000, 7, {}, request, 511, 7, 8));
    }
    const std::array<A::Request, 2> requests{
        {{0, A::RequestKind::Receive}, {0, A::RequestKind::Adc}}};
    auto both = irq(byte);
    both.cpu.ram[0xcb] = 0;
    auto tie = run(both, 1000, 1, {}, requests);
    const auto *accepted = findEvent(tie, K::InterruptAcceptance);
    check(accepted && accepted->address == 0x20,
          "ADC wins a simultaneous UART request at instruction boundary");
    at(tie, K::RamWrite, 0xffcb, 32, 1);
    at(tie, K::InterruptReturn, 0xf000, 59, 0);
    check(tie.status == A::Status::UnsupportedPath && tie.cpu.registers.pc == 0x05a0 &&
              tie.cpu.now == 129,
          "nonwrap ADC short-return then pending RX reaches05A0 at129states");
    both.cpu.ram[0xcb] = 0xff;
    auto wrap = run(both, 1000, 1, {}, requests);
    at(wrap, K::RamWrite, 0xffcb, 32, 0);
    check(wrap.status == A::Status::UnsupportedPath && wrap.cpu.registers.pc == 0x054b &&
              wrap.cpu.now == 46 && !findEvent(wrap, K::InterruptReturn),
          "ADC counter wrap reaches unsupported full054B before any handler effect");
    equality(wrap, run(both, 1000, 1000, {}, requests, 511, 7, 8));
    auto invalid = procedure(0x9e8);
    A::Events events;
    std::array<U::Event, 8> storage{};
    U::EventBuffer wire{storage.data(), storage.size(), 0};
    const auto before = invalid;
    auto bad = A::advanceTo(invalid.cpu, invalid.uart, {}, {}, U::noEvent, events, wire);
    check(bad.status == A::Status::InvalidState && sameCpu(invalid.cpu, before.cpu) &&
              uartState(invalid.uart) == uartState(before.uart) && events.count == 0 &&
              wire.count == 0,
          "oversized absolute target rejected before mutation");
}
void producerBackpressure() {
    auto seed = procedure(0x9e8, 0x7f);
    seed.cpu.ram[0xc2] = 47;
    for (unsigned i = 0; i < 47; ++i)
        seed.cpu.ram[i] = static_cast<std::uint8_t>(0x80 + i);
    const auto original = seed.cpu.ram;
    auto blocked = run(seed, 1000);
    check(blocked.status == A::Status::ReachedTarget && blocked.cpu.ram[0xc1] == 0 &&
              blocked.cpu.ram[0xc2] == 47,
          "47 queued slots block producer until a slot is consumed");
    check(std::equal(original.begin(), original.begin() + 48, blocked.cpu.ram.begin()) &&
              !findEvent(blocked, K::RamWrite),
          "full FIFO wait neither overwrites data nor publishes tail");
    // A coherent already-full TXB becomes empty on the configured128-state
    // launch. Its real FST request preempts the waiting producer and frees a
    // slot; no synthetic head edit or invented foreground instruction occurs.
    seed.cpu.interruptEnabled = true;
    seed.uart.fst = false;
    seed.uart.txBufferFull = true;
    seed.uart.txBuffer = 0x22;
    seed.uart.idleLaunch = 128;
    auto released = run(seed, 2000);
    const auto *head = findEvent(released, K::RamWrite, 0xffc1);
    const auto *slot = findEvent(released, K::RamWrite, 0xff2f);
    const auto *tail = findEvent(released, K::RamWrite, 0xffc2);
    check(released.status == A::Status::AwaitingForeground && released.cpu.ram[0xc1] == 1 &&
              released.cpu.ram[0xc2] == 0 && released.cpu.ram[47] == 0x7f,
          "real transmitter-empty IRQ releases one slot and producer wraps publication");
    check(head && slot && tail && head->value == 1 && slot->value == 0x7f && tail->value == 0 &&
              head->states < slot->states && slot->states < tail->states,
          "consumer head publication precedes slot write and new tail publication");
    const auto *tx = findEvent(released, K::TxBufferWrite);
    check(tx && tx->value == 0x80, "real consumer sends oldest FIFO byte to release producer");
    check(std::equal(original.begin() + 1, original.begin() + 47, released.cpu.ram.begin() + 1),
          "backpressure release preserves all remaining queued bytes");
    equality(released, run(seed, 2000, 1));
    equality(released, run(seed, 2000, 83, {}, {}, 511, 7, 8));
}
void activeFrameRouteGuard() {
    // Enter the actual TX dispatcher just after a real TXB->shifter transfer:
    // TXB is empty/FST pending and an entire1280-state frame remains. This is
    // the reachable worst remaining-frame bound, not an arbitrary fullTXB state.
    for (unsigned phase = 0; phase < 128; ++phase)
        for (unsigned initial : {0xfd, 0xf9}) {
            const auto marker = initial ^ 4u;
            const std::array<std::uint8_t, 2> queue{static_cast<std::uint8_t>(marker), 0x88};
            auto seed = irq(queue, 0, initial);
            U::Configuration config{static_cast<std::uint8_t>(phase)};
            std::array<U::Event, 32> storage{};
            U::EventBuffer wire{storage.data(), storage.size(), 0};
            (void)U::testAndClearFst(seed.uart);
            check(U::writeTxBuffer(seed.uart, config, 0x55, wire) == U::Status::Ok,
                  "active-frame route fixture starts from actual TXB write");
            const std::uint64_t launch = phase ? phase : 128;
            check(U::advanceTo(seed.uart, config, launch, wire) == U::Status::Ok &&
                      seed.uart.frameActive && !seed.uart.txBufferFull && seed.uart.fst,
                  "real launch provides active shifter plus empty-buffer request");
            seed.cpu.now = launch;
            const auto pcTime = launch + (marker == 0xfd ? 1751u : 1765u);
            auto result = run(seed, pcTime + 165, 10000, config);
            at(result, K::PortCWrite, 2, pcTime, marker);
            const auto end =
                std::find_if(result.wire.begin(), result.wire.end(), [](const auto &e) {
                    return e.kind == U::EventKind::FrameEnd && e.frameOrdinal == 1;
                });
            check(end != result.wire.end() && end->states == launch + 1280 && end->states < pcTime,
                  "old routed frame completes before changed-marker PC commit");
            unsigned oldBits = 0;
            for (const auto &e : result.wire)
                if (e.states < pcTime) {
                    const bool tx = (e.pinLevels & 1) != 0;
                    const bool module = (e.pinLevels & 2) != 0;
                    const bool midi = (e.pinLevels & 4) != 0;
                    check(module == ((initial & 4) ? tx : true) &&
                              midi == ((initial & 4) ? true : tx),
                          "old route remains connected throughout every remaining physical frame "
                          "bit");
                    if (e.kind == U::EventKind::BitBegin && e.frameOrdinal == 1) {
                        const auto i = e.bitIndex;
                        const bool expected = i == 9 || (i >= 1 && i <= 8 && bool(0x55u & (1u << (i - 1))));
                        check(i >= 1 && i <= 9 && e.states == launch + 128 * i && tx == expected,
                              "remaining frame uses independent8N1 bit/timing oracle");
                        ++oldBits;
                    }
                }
            check(oldBits == 9,
                  "all nine remaining data/stop boundaries observed before rerouting");
            check(result.uart.portC == marker, "guard eventually switches to requested route");
        }
}
int runTests() {
    literalLedgers();
    callerAndChunking();
    interruptsAndBoundaries();
    producerBackpressure();
    activeFrameRouteGuard();
    std::cout << "{\"assertions\":" << assertions << ",\"failures\":" << failures << "}\n";
    return failures ? 1 : 0;
}
#ifndef ASSIGNER_ORACLE_DRIVER
int main() { return runTests(); }
#endif
