#pragma once

#include <array>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <string>
#include <type_traits>

// Offline-only writer. Hexadecimal literals preserve every binary32/64 bit.
namespace frozen_table_writer
{
inline std::filesystem::path destination;

template <class T>
void value(std::ostream& out, T item)
{
    if constexpr (std::is_floating_point_v<T>)
    {
        out << std::hexfloat << item;
        if constexpr (std::is_same_v<T, float>) out << 'f';
    }
    else out << +item;
}

template <class T, std::size_t size>
void value(std::ostream& out, const std::array<T, size>& items)
{
    out << "{{\n";
    for (const auto& item : items) { value(out, item); out << ",\n"; }
    out << "}}";
}

template <class Write>
void file(const char* name, Write write)
{
    std::ofstream out(destination / (std::string(name) + ".inc"));
    out.exceptions(std::ios::failbit | std::ios::badbit);
    out << "// Generated by Tools/generate_frozen_tables.py from the native DSP builders.\n";
    write(out);
    out << '\n';
}

template <class T>
void scalar(const char* name, const T& item)
{
    file(name, [&](auto& out) { value(out, item); });
}
} // namespace frozen_table_writer
