// Renders musical short demonstrations for well-known factory presets
// through the same JUCE-free engine used by the plug-in, at 24-bit/44.1 kHz
// on the deepest 4x oversampling rung with Exact tanh and half-step Merson solver.

#include "PresetScores.h"
#include "DSP/YouKnowEngine.h"
#include "DSP/YouKnowPresets.h"
#include "DSP/YouKnowProductFidelity.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <future>
#include <iomanip>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

namespace
{
using namespace youknow;
using namespace youknow::preset_demos;

constexpr double sampleRate = 44100.0;
constexpr int blockSize = 256;
constexpr int requestedQuality = 4;
constexpr int bitsPerSample = 24;
constexpr double normalisedPeak = 0.7079457843841379; // -3 dBFS
constexpr double prefaceSeconds = 0.10;
constexpr double keyUpGuardSeconds = 0.005;
constexpr double maximumAbsoluteDcMean = 0.005;
constexpr double maximumEdgeMagnitude = 0.01;

constexpr const char* tableBeginMarker =
    "<!-- preset-demos-table-begin: regenerated by YouKnowRenderPresetDemos;"
    " edits between the markers are overwritten -->";
constexpr const char* tableEndMarker = "<!-- preset-demos-table-end -->";

struct Audio
{
    std::vector<float> left;
    std::vector<float> right;
};

struct RenderResult
{
    PresetDemo demo;
    double seconds = 0.0;
    double rawPeak = 0.0;
    double gain = 1.0;
    double rmsDbfs = -100.0;
    double peakDbfs = 0.0;
    double normalisationDb = 0.0;
    double dc = 0.0;
};

void require (bool condition, const std::string& message)
{
    if (! condition)
        throw std::runtime_error (message);
}

std::filesystem::path instrumentReadme (const std::filesystem::path& directory)
{
    auto normalised = directory.lexically_normal();
    if (normalised.filename().empty())
        normalised = normalised.parent_path();

    if (normalised.filename() != "presets"
        || normalised.parent_path().filename() != "audio"
        || normalised.parent_path().parent_path().filename() != "Docs")
        return {};

    return normalised.parent_path().parent_path().parent_path() / "README.md";
}

std::string formatSignedDb (double value)
{
    char digits[32];
    std::snprintf (digits, sizeof digits, "%.1f", std::fabs (value));
    const bool negative = value < 0.0 && std::strcmp (digits, "0.0") != 0;
    return std::string (negative ? "\xE2\x88\x92" : "+") + digits;
}

void writeWav24 (const std::filesystem::path& path, const Audio& a)
{
    std::ofstream f (path, std::ios::binary);
    require (static_cast<bool> (f), "Cannot open " + path.string());

    const auto le = [&f] (std::uint32_t n, int bytes)
    {
        for (int i = 0; i < bytes; ++i)
            f.put (static_cast<char> ((n >> (8 * i)) & 0xffu));
    };

    constexpr std::uint16_t channels = 2u;
    constexpr std::uint32_t bytesPerSample = bitsPerSample / 8;
    const auto frames = static_cast<std::uint32_t> (a.left.size());
    const std::uint32_t dataBytes = frames * channels * bytesPerSample;

    f.write ("RIFF", 4);
    le (36u + dataBytes, 4);
    f.write ("WAVEfmt ", 8);
    le (16u, 4);
    le (1u, 2); // PCM
    le (channels, 2);
    le (static_cast<std::uint32_t> (sampleRate), 4);
    le (static_cast<std::uint32_t> (sampleRate) * channels * bytesPerSample, 4);
    le (channels * bytesPerSample, 2);
    le (bitsPerSample, 2);
    f.write ("data", 4);
    le (dataBytes, 4);

    // Deterministic 24-bit TPDF dither
    std::uint32_t state = 0x5a1f29b7u;
    const auto uniform = [&state] ()
    {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        return static_cast<double> (state) / 4294967296.0;
    };

    for (std::size_t i = 0; i < a.left.size(); ++i)
    {
        for (float value : { a.left[i], a.right[i] })
        {
            const double firstNoise = uniform();
            const double secondNoise = uniform();
            const auto quantized = static_cast<std::int32_t> (
                std::llround (static_cast<double> (value) * 8388607.0 + firstNoise - secondNoise));
            const auto clamped = std::clamp (quantized, -8388608, 8388607);
            le (static_cast<std::uint32_t> (clamped) & 0xffffffu, 3);
        }
    }
}

RenderResult renderDemo (const PresetDemo& d, const std::filesystem::path& directory)
{
    const double secondsPerBeat = 60.0 / d.tempo;
    const auto frameAt = [secondsPerBeat] (double beat)
    {
        return static_cast<std::int64_t> (
            std::llround ((prefaceSeconds + beat * secondsPerBeat) * sampleRate));
    };

    struct Gate { std::int64_t frame; int note; bool on; };
    std::vector<Gate> gates;

    for (const auto& e : d.events)
    {
        const auto on = frameAt (e.beat);
        const auto off = std::max (on + 1, frameAt (e.beat + e.length)
                                   - static_cast<std::int64_t> (keyUpGuardSeconds * sampleRate));
        for (int noteNum : e.notes)
        {
            gates.push_back ({ on, noteNum, true });
            gates.push_back ({ off, noteNum, false });
        }
    }

    std::stable_sort (gates.begin(), gates.end(), [] (const Gate& a, const Gate& b)
    {
        return a.frame != b.frame ? a.frame < b.frame : a.on < b.on;
    });

    auto engine = std::make_unique<YouKnowEngine>();
    ProductFidelityProfile::configureBeforePrepare (*engine);
    engine->selectConverterTimingProfile (YouKnowEngine::ConverterTimingProfile::MeasuredChartGeometry);
    engine->prepare (sampleRate, blockSize, requestedQuality);

    auto p = loadPresetParameters (d.slot);
    engine->setParameters (p);
    engine->setPitchBend (0);
    engine->setModWheel (0);

    const double tailSeconds = std::max (d.tailSeconds,
        YouKnowEngine::envelopeReleaseSeconds (p.release) + 0.5);
    const auto totalFrames = frameAt (d.musicBeats)
                           + static_cast<std::int64_t> (std::llround (tailSeconds * sampleRate));

    Audio audio;
    audio.left.resize (static_cast<std::size_t> (totalFrames), 0.0f);
    audio.right.resize (static_cast<std::size_t> (totalFrames), 0.0f);

    std::array<float, blockSize> preLeft {}, preRight {};
    // Pre-roll physical nodes
    for (int i = 0; i < static_cast<int> (0.37 * sampleRate); i += blockSize)
        engine->process (preLeft.data(), preRight.data(), blockSize);

    std::size_t nextGate = 0;
    int voicePeak = 0;

    for (std::int64_t frame = 0; frame < totalFrames;)
    {
        while (nextGate < gates.size() && gates[nextGate].frame <= frame)
        {
            const auto& gate = gates[nextGate++];
            if (gate.on)
                engine->noteOn (gate.note, 1);
            else
                engine->noteOff (gate.note);
        }

        auto count = std::min<std::int64_t> (blockSize, totalFrames - frame);
        if (nextGate < gates.size())
            count = std::min (count, gates[nextGate].frame - frame);

        engine->process (audio.left.data() + frame, audio.right.data() + frame,
                         static_cast<int> (count));
        voicePeak = std::max (voicePeak, engine->getActiveVoiceCount());
        frame += count;
    }

    require (voicePeak > 0, std::string (d.slot) + " rendered no active voices");

    double rawPeak = 0.0;
    double squareSum = 0.0;
    double leftSum = 0.0;
    double rightSum = 0.0;

    for (std::size_t i = 0; i < audio.left.size(); ++i)
    {
        const double l = audio.left[i];
        const double r = audio.right[i];
        require (std::isfinite (l) && std::isfinite (r),
                 std::string (d.slot) + " produced non-finite audio");
        rawPeak = std::max ({ rawPeak, std::abs (l), std::abs (r) });
        squareSum += 0.5 * (l * l + r * r);
        leftSum += l;
        rightSum += r;
    }

    require (rawPeak >= 1.0e-4, std::string (d.slot) + " rendered silence");

    const double gain = normalisedPeak / rawPeak;
    const auto frames = static_cast<double> (audio.left.size());
    const double dc = std::max (std::abs (leftSum * gain / frames),
                                std::abs (rightSum * gain / frames));
    require (dc <= maximumAbsoluteDcMean,
             std::string (d.slot) + " DC offset exceeds threshold");

    // Apply gain and ending fade
    constexpr std::size_t fadeFrames = static_cast<std::size_t> (0.050 * sampleRate);
    const std::size_t fadeStart = audio.left.size() > fadeFrames
                                ? audio.left.size() - fadeFrames : 0;

    for (std::size_t i = 0; i < audio.left.size(); ++i)
    {
        double g = gain;
        if (i >= fadeStart && fadeFrames > 1)
        {
            const double phase = static_cast<double> (i - fadeStart)
                               / static_cast<double> (fadeFrames - 1);
            g *= 0.5 * (1.0 + std::cos (3.14159265358979323846 * phase));
        }
        audio.left[i] = static_cast<float> (audio.left[i] * g);
        audio.right[i] = static_cast<float> (audio.right[i] * g);
    }

    const double firstEdge = std::max (std::abs (audio.left.front()),
                                      std::abs (audio.right.front()));
    const double lastEdge = std::max (std::abs (audio.left.back()),
                                     std::abs (audio.right.back()));
    require (firstEdge <= maximumEdgeMagnitude && lastEdge <= maximumEdgeMagnitude,
             std::string (d.slot) + " edge magnitude exceeds threshold");

    const auto filePath = directory / d.filename;
    writeWav24 (filePath, audio);

    RenderResult res;
    res.demo = d;
    res.seconds = static_cast<double> (totalFrames) / sampleRate;
    res.rawPeak = rawPeak;
    res.gain = gain;
    res.peakDbfs = 20.0 * std::log10 (rawPeak);
    res.normalisationDb = 20.0 * std::log10 (gain);
    const double meanEnergy = squareSum * (gain * gain) / frames;
    res.rmsDbfs = meanEnergy > 1.0e-12 ? 10.0 * std::log10 (meanEnergy) : -120.0;
    res.dc = dc;
    return res;
}

bool updateReadmeTable (const std::filesystem::path& directory,
                        const std::vector<RenderResult>& results)
{
    const auto readmePath = instrumentReadme (directory);
    if (readmePath.empty() || ! std::filesystem::exists (readmePath))
        return true;

    std::ifstream input (readmePath, std::ios::binary);
    std::string readme ((std::istreambuf_iterator<char> (input)),
                        std::istreambuf_iterator<char>());
    input.close();

    const auto beginPos = readme.find (tableBeginMarker);
    const auto endPos = readme.find (tableEndMarker);
    if (beginPos == std::string::npos || endPos == std::string::npos || endPos < beginPos)
    {
        // Table markers not found, skip updating
        return true;
    }

    std::string table = "\n| Preset | Name | Category | Length | Rendered peak | Normalisation | What to hear |\n"
                        "| --- | --- | --- | ---: | ---: | ---: | --- |\n";

    for (const auto& r : results)
    {
        char row[512];
        std::snprintf (row, sizeof row,
                       "| [`%s`](Docs/audio/presets/%s) | %s | %s | %.1f s | %s dBFS | %s dB | %s |\n",
                       r.demo.slot, r.demo.filename, r.demo.title, r.demo.category,
                       r.seconds, formatSignedDb (r.peakDbfs).c_str(),
                       formatSignedDb (r.normalisationDb).c_str(),
                       r.demo.musicalDescription);
        table += row;
    }

    const auto contentStart = beginPos + std::strlen (tableBeginMarker);
    const auto updated = readme.substr (0, contentStart) + table + readme.substr (endPos);
    if (updated == readme)
        return true;

    std::ofstream output (readmePath, std::ios::binary | std::ios::trunc);
    output << updated;
    output.close();
    std::printf ("Updated the preset-demos table in %s\n", readmePath.string().c_str());
    return ! output.fail();
}

int runSmokeTest (const std::filesystem::path& directory)
{
    std::error_code error;
    std::filesystem::create_directories (directory, error);
    auto demo = brassSet1Demo();
    demo.musicBeats = 3.0;
    demo.events.resize (2);
    demo.filename = "smoke-test.wav";
    const auto res = renderDemo (demo, directory);
    const auto path = directory / demo.filename;
    require (std::filesystem::exists (path), "smoke WAV was not created");
    std::filesystem::remove (path, error);
    std::printf ("Preset demo smoke test passed (peak %.3f, %.1f s)\n",
                 res.rawPeak, res.seconds);
    return 0;
}

} // namespace

int main (int argc, char** argv)
{
    try
    {
        bool smoke = false;
        std::filesystem::path directory = "Docs/audio/presets";

        for (int i = 1; i < argc; ++i)
        {
            const std::string arg = argv[i];
            if (arg == "--smoke")
                smoke = true;
            else if (arg == "--help" || arg == "-h")
            {
                std::printf ("usage: YouKnowRenderPresetDemos [--smoke] [output-directory]\n");
                return 0;
            }
            else
            {
                directory = arg;
            }
        }

        if (smoke)
            return runSmokeTest (directory);

        std::error_code error;
        std::filesystem::create_directories (directory, error);
        require (std::filesystem::is_directory (directory),
                 "Invalid directory: " + directory.string());

        const auto demos = allPresetDemos();
        std::printf ("Rendering %zu factory preset demos into %s...\n",
                     demos.size(), directory.string().c_str());

        std::vector<std::future<RenderResult>> futures;
        futures.reserve (demos.size());
        for (const auto& d : demos)
        {
            futures.push_back (std::async (std::launch::async, [d, directory] {
                return renderDemo (d, directory);
            }));
        }

        std::vector<RenderResult> results;
        results.reserve (futures.size());
        for (auto& f : futures)
        {
            results.push_back (f.get());
            const auto& r = results.back();
            std::printf ("Rendered %-4s %-22s %5.1f s, raw peak %6.3f (%s dBFS), norm %s dB\n",
                         r.demo.slot, r.demo.filename, r.seconds, r.rawPeak,
                         formatSignedDb (r.peakDbfs).c_str(),
                         formatSignedDb (r.normalisationDb).c_str());
        }

        updateReadmeTable (directory, results);
        std::printf ("Successfully rendered all %zu factory preset demos.\n", results.size());
        return 0;
    }
    catch (const std::exception& e)
    {
        std::fprintf (stderr, "Preset demos render failed: %s\n", e.what());
        return 1;
    }
}
